site_name: Easymath-wiki
site_url: https://easymath-wiki.com
site_author: easymath-wiki
site_description: >-
  Know the things about math where you want to know immediately.



theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: overrides
markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - pymdownx.snippets
  - attr_list
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - meta
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - footnotes
  - pymdownx.critic
  - admonition
  - md_in_html
  - codehilite:
      guess_lang: false
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.betterem:
      smart_enable: 'underscore'
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - css/extra.css
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Easymath-wiki/Easymath-wiki
  disqus:
  cusdis:
    host: https://cusdis.kxxt.tech
    lang: zh-cn
    app_id: 4cd3d461-7504-4788-8374-ac6df6d2cbb7

repo_name: Easymath-wiki
repo_url: https://github.com/Easymath-wiki/Easymath-wiki
edit_uri: edit/master/docs

extra_javascript:
  - https://cdn.bootcdn.net/ajax/libs/mathjax/2.7.9/MathJax.js
  - javascripts/config.js
copyright: Copyright &copy; 2021 Easymath Wiki Team
