site_name: Easymath-wiki
site_url: https://easymath-wiki.com
site_author: Humor
site_description: >-
  Know the things about math where you want to know immediately.



theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - pymdownx.snippets
  - attr_list
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - meta
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - footnotes
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - md_in_html
  - codehilite:
      guess_lang: false
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Huang-Shijie-SDUWH/Easymath-wiki


repo_name: Huang-Shijie-SDUWH/Easymath-wiki
repo_url: https://github.com/Huang-Shijie-SDUWH/Easymath-wiki
edit_uri: edit/master/docs

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: Copyright &copy; 2021 Easymath Wiki Team